### ISSUE TITLE
Error in content element listview

### ISSUE THREAD

**Issue by stefansl** [markocupic/contao-heroimage-bundle#1]
My heroimage produces an error in the content element listview:
`Argument 1 passed to Markocupic\ContaoHeroimageBundle\Controller\ContentElement\HeroimageElementController::__construct() must be an instance of Contao\CoreBundle\Framework\ContaoFramework, string given, called in /var/www/customer/var/cache/dev/ContainerFLMxP7i/getContao_Fragment_Contao_ContentElement_HeroimageElementService.php on line 27`

Contao 4.12.1
PHP 7.4.24

**Comment by stefansl** [comment]
Ok, I just saw, you fixed this already in dev-master. Would be nice to have a new release :) Btw. great bundle 👍

**Comment by markocupic** [comment]
Hi Stefan
Please try version 1.0.2 (untested) and give me a short feedback.

**Comment by stefansl** [comment]
works like a charm. thx! :)
